/*
 *
 * Task code generated by SAS Studio 3.3 
 *
 * Generated on '3/16/16, 1:05 AM' 
 * Generated by 'Sergiu Buciumas' 
 * Generated on server 'SASCOMPUTE3.KENNESAW.EDU' 
 * Generated on SAS platform 'AIX AIX 64 7.1' 
 * Generated on SAS version '9.04.01M2P07232014' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36' 
 * Generated on web client 'https://phdsas.kennesaw.edu/SASStudio/main?locale=en_US&zone=GMT-04%253A00' 
 *
 */

ods graphics / imagemap=on;

proc reg data=DATAREG.B4;
    model y = x1 x2 x3 x4 x5 x6 x7 x8 x9 / r p clm cli influence;
    run;
quit;


ods graphics / imagemap=on;

proc reg data=DATAREG.B10;
    model y = x1 x2 / r PRESS;
    run;
quit;